-- Database Table

DROP TABLE IF EXISTS DBS;
CREATE TABLE DBS (
	DATABASE_ID BIGINT NOT NULL AUTO_INCREMENT,
	DRIVER_NAME VARCHAR(64),
	NAME VARCHAR(16) NOT NULL,
	PASSWORD VARCHAR(16),
	URL VARCHAR(64) NOT NULL,
	USER_ID VARCHAR(16),
	USERNAME VARCHAR(16),
	CONSTRAINT PK_DBS PRIMARY KEY (DATABASE_ID)
);

DROP INDEX IF EXISTS UK_ON_DATABASE_ID;
CREATE UNIQUE INDEX UK_ON_DATABASE_ID ON DBS (DATABASE_ID);

DROP INDEX IF EXISTS UK_ON_DATABASE_NAME;
CREATE UNIQUE INDEX UK_ON_DATABASE_NAME ON DBS (NAME);

-- Collection Table

DROP TABLE IF EXISTS COLLS;
CREATE TABLE COLLS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DATABASE_ID BIGINT,
	ALIAS VARCHAR(32) NOT NULL,
	KIND VARCHAR(16),
	NAME VARCHAR(32) NOT NULL,
	CONSTRAINT PK_COLLS PRIMARY KEY (ID)
);

DROP INDEX IF EXISTS UK_ON_COLL_ID;
CREATE UNIQUE INDEX UK_ON_COLL_ID ON COLLS (ID);

DROP INDEX IF EXISTS UK_ON_DATABASE_ID_AND_ALIAS;
CREATE UNIQUE INDEX UK_ON_DATABASE_ID_AND_ALIAS ON COLLS (DATABASE_ID,ALIAS);

